import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full bg-blue-50 font-sans text-base antialiased dark:bg-slate-900 dark:text-white">
        {children}
      </body>
    </html>
  )
}
